version: '3.8'
services:
  parmanus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parmanus
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - model-data:/models
      # Optional: Mount your application code for development
      # - ./:/app/ParManus
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
volumes:
  model-data:
