version: '3.8'

services:
  openmanus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openmanus
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      # Persistent storage for models
      - ollama-models:/root/.ollama
      # Optional: Mount your application code for development
      # - ./:/app/OpenManus
    ports:
      # Default port for OpenManus (adjust as needed)
      - "8000:8000"
      # Ollama API port (if you want to access it from host)
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama-models:
    # Named volume for persistent Ollama model storage
    # Models will be downloaded once and cached for future container runs
