# Simple Test Configuration for ParManusAI
# Optimized for visible browser testing with NO LOG SPAM

[llm]
model = "llama-jb"
model_path = "/models/llama-jb.gguf"
max_tokens = 1024  # Reduced for faster responses
temperature = 0.0

# GPU Settings - MINIMAL MONITORING
[gpu]
force_cuda = true
force_gpu_layers = 20
enable_monitoring = false       # DISABLE GPU monitoring completely
auto_cleanup = false           # Disable auto cleanup
fallback_to_cpu = true

# Browser Settings - VISIBLE MODE
[browser]
headless = false            # Browser window will be visible
disable_security = true     # Faster loading
timeout = 30

# Agent Settings
[agent]
max_steps = 10              # Fewer steps for testing
stuck_detection = "basic"   # Simpler detection
circuit_breaker = true

# Minimal Logging
[logging]
level = "WARNING"           # Only show warnings and errors
reduce_verbosity = true
enable_file_logging = false

# Simple Memory Management
[memory]
save_session = false
recover_last_session = false
memory_compression = false

# Disable All Monitoring
[monitoring]
enable_metrics = false      # Disable for cleaner output
gpu_monitoring = false      # Disable for cleaner logs
memory_monitoring = false   # Disable memory monitoring
